Added alternative ctrl+n, ctrl+p for navigation down and up in anyrun and rofi configs. Updated launchwin script to handle windows boot entry not found and added echo statements. Deleted unused theme.rasi in rofi config which was used for testing

diff --git a/bin/.local/bin/launchwin b/bin/.local/bin/launchwin
--- a/bin/.local/bin/launchwin
+++ b/bin/.local/bin/launchwin
@@ -1,4 +1,22 @@
 #!/bin/bash
+
+# Find Windows boot entry number in GRUB
 windows_entry=$(sudo awk -F"'" '/menuentry / && /Windows Boot Manager/ {print i; exit} /menuentry / {i++}' /boot/grub/grub.cfg)
+
+if [ -z "$windows_entry" ]; then
+  echo "Error: Can't find windows entry in GRUB"
+  exit 1
+fi
+
+echo "Found windows entry nr. $windows_entry"
+
+# set next boot to windows
 sudo grub-reboot "$windows_entry"
+
+echo "Rebooting now"
+
+# wait a tiny bit
+sleep 0.2
+
+# Reboot
 sudo reboot
